In [2]:
import numpy as np
from timeit import default_timer as timer

In [2]:
print(np.__version__)

1.23.5


# Array  - shape , dtype , ndim , size , itemsize

In [10]:
# 1D Array
a = np.array([1,2,3])
print(a)
print(a.shape) # shape (rows , columns)
print(a.dtype) # datatype
print(a.ndim)  # dimension of array
print(a.size)  # print the no of elements
print(a.itemsize)  # =>> each element 32 bits or 4 bytes

[1 2 3]
(3,)
int32
1
3
4


In [11]:
b = a + np.array([4])
b

array([5, 6, 7])

## LIST vs ARRAY

In [17]:
# dot product
l1 = [1,2,3]
l2 = [4,5,6]

# dot product for list

dot = 0
for i in range(len(l1)):
    dot += l1[i]  * l2[i]
print(dot)  

# 1
a = np.array(l1)
b = np.array(l2)

dot = np.dot(a,b)
print(dot)

#2

sum1 = a * b
dot = np.sum(sum1)
print(dot)

#3
dot = a @ b
print(dot)

32
32
32
32


In [25]:
# time comparison

a = np.random.randn(1000)
b = np.random.randn(1000)

A = list(a)
B = list(b)

T = 1000

def dot1():
    dot = 0
    for i in range(len(A)):
        dot += A[i]  * B[i]
    return dot

def dot2():
    dot = np.dot(a,b)
    return dot    
start = timer()
for t in range(T):
    dot1()
end = timer()
t1 = end - start


start = timer()
for t in range(T):
    dot2()
end = timer()
t2 = end - start

print('list calculation' , t1)
print('np.dot',t2)
print('ratio' , t1 / t2)


list calculation 0.30174629999964964
np.dot 0.0024354999986826442
ratio 123.8950113581866


# MULTIDEMENSIONAL ARRAY

In [45]:
# Multidimentional Arrays

a = np.array([[1,2,3] , [4 ,5 ,6]])
print(a)
print(a.shape)

print(a[0][0])  # a[row][column]
print(a[0,0])   # ==>> works on list as well

print()

print(a[0 , :]) # first row
print(a[: , 0]) # first column

print()

print(a.T)  # Trnaspose of the array

print()

b = np.array([[1,2] , [3,4]])
print(np.linalg.inv(b))  # Inverse of the array


print()

print(np.linalg.det(b))  # Determinant of the array

# Two use cases of diagonal functional

print()

print(b)
print()

print(np.diag(b))  # Diagonal elements

c = np.diag(b)
print()
print(np.diag(c))  # Diagonal Matrix

[[1 2 3]
 [4 5 6]]
(2, 3)
1
1

[1 2 3]
[1 4]

[[1 4]
 [2 5]
 [3 6]]

[[-2.   1. ]
 [ 1.5 -0.5]]

-2.0000000000000004

[[1 2]
 [3 4]]

[1 4]

[[1 0]
 [0 4]]


In [16]:
a = np.array([[1 , 2] , [3 , 4] , [5,6]])
print(a , "\n")

print(a[0,:] , "\n")

print(a[:,1] , "\n")

bool_inx = a > 2
print(bool_inx , "\n")

print(a[bool_inx])  # Only prits the elements which satisfy the condition

print()
print(a[a > 2])



[[1 2]
 [3 4]
 [5 6]] 

[1 2] 

[2 4 6] 

[[False False]
 [ True  True]
 [ True  True]] 

[3 4 5 6]

[3 4 5 6]


In [24]:
b = np.where(a > 2 , a , 0) # Return elements greater than 2 and replace elements which are less than 2 with 0
print(b)

[[0 0]
 [3 4]
 [5 6]]


In [29]:
# Fancy indexing

a = np.array([10 , 20 , 35 , 65 , 45 , 58 , 78])
b = [1 , 6 , 2 ]

print(a[b] )

even = np.argwhere(a % 2 == 0).flatten()
print("\n" , a[even])
 

[20 78 35]

 [10 20 58 78]
